# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a6cc409cd33b1c2dd8366220c6b7f3de49836f3cbd2ef4c2add95240edaf1947ff5ffe9d0324690f0da270a0b48b3e30a5331bee2b4dfd36e81faa134c9fa2

test:
  secret_key_base: b8dcf26c19e949d78dbcbec15fe3f8140c18459fc47314bd6e1f06f58ee1abfc46ae0e66c358c5099d2016bc265075f6523c37aae227c743454739652bb01ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
